package eu.essi_lab.vlab.core.configuration;

/**
 * @author Mattia Santoro
 */
public enum BPStaticConfigurationParameters {
	BP_COMPUTE_INFRA_PROVIDER("eu.essi_lab.vlab.compute.provider", false),

	AWS_EXECUTE_ECS_REGION("eu.essi_lab.vlab.aws.execute.ecs.region", false),
	AWS_EXECUTE_ECS_ACCESS_KEY("eu.essi_lab.vlab.aws.execute.ecs.accessKey", true),
	AWS_EXECUTE_ECS_SECRET_KEY("eu.essi_lab.vlab.aws.execute.ecs.secretKey", true),
	AWS_EXECUTE_MODEL_CLUSTER_NAME("eu.essi_lab.vlab.aws.execute.ecs.cluster.model.name", false),
	AWS_MODEL_EXECUTION_AUTO_SCALING_GROUPS("eu.essi_lab.vlab.aws.asg.groups", false),

	COMPUTE_INFRASTRUCTURE_ID("eu.essi_lab.vlab.execute.infrastructure.identifier", false),
	COMPUTE_INFRASTRUCTURE_LABEL("eu.essi_lab.vlab.execute.infrastructure.label", false),
	COMPUTE_INFRASTRUCTURE_TYPE("eu.essi_lab.vlab.execute.infrastructure.type", false),

	BP_EXECUTABLE_STORAGE_TYPE("eu.essi_lab.vlab.storage.executable.type", false),

	RDF_REPOSITORY("eu.essi_lab.vlab.storage.rdf", false),
	RDF_UPDATE_REPOSITORY("eu.essi_lab.vlab.storage.rdf.update", false),
	AWS_DEPLOY_ECS_ACCESS_KEY("eu.essi_lab.vlab.aws.deploy.ecs.accessKey", true),
	AWS_DEPLOY_ECS_SECRET_KEY("eu.essi_lab.vlab.aws.deploy.ecs.secretKey", true),
	AWS_DEPLOY_ECS_REGION("eu.essi_lab.vlab.aws.deploy.ecs.region", false),
	AWS_ECS_CLUSTER_NAME("eu.essi_lab.vlab.aws.ecs.cluster.name", false),
	AWS_ECS_EFS_FOLDER("eu.essi_lab.vlab.aws.ecs.efsfolder", false),
	AWS_ECS_TASK_CONTAINER_NAME("eu.essi_lab.vlab.model.task.container.name", false, "AutogeneratedBPEngineContainer"),

	AWS_ASG_ACCESS_KEY("eu.essi_lab.vlab.aws.asg.accessKey", true),
	AWS_ASG_SECRET_KEY("eu.essi_lab.vlab.aws.asg.secretKey", true),

	AWS_LOG_ACCESS_KEY("eu.essi_lab.vlab.aws.log.accessKey", true),
	AWS_LOG_SECRET_KEY("eu.essi_lab.vlab.aws.log.secretKey", true),
	AWS_MODEL_EXECUTION_LOG_GROUP("eu.essi_lab.vlab.aws.ecs.model.loggroup", false),
	AWS_MODEL_EXECUTION_LOG_PREFIX("eu.essi_lab.vlab.aws.ecs.model.logprefix", false, "bpenginemodelexecution"),
	AWS_DEPLOY_ECS_LOG_PREFIX("eu.essi_lab.vlab.aws.deploy.ecs.logprefix", false, "bpenginedeploy"),
	AWS_DEPLOY_ECS_LOG_GROUP("eu.essi_lab.vlab.aws.deploy.ecs.loggroup", false),
	AWS_LOG_REGION("eu.essi_lab.vlab.aws.log.region", false),

	PREPEARE_IMAGE("eu.essi_lab.vlab.preparejob.image", false),
	AWS_CLI_IMAGE("eu.essi_lab.vlab.awsclijob.image", false),

	AWS_SQS_BP_RUN_QUEQUE_NAME("eu.essi_lab.vlab.aws.sqs.bprun.queque", false),
	AWS_SQS_ACCESS_KEY("eu.essi_lab.vlab.aws.sqs.accessKey", true),
	AWS_SQS_SECRET_KEY("eu.essi_lab.vlab.aws.sqs.secretKey", true),
	AWS_SQS_REGION("eu.essi_lab.vlab.aws.sqs.region", false),
	BP_RUN_QUEQUE_SERVER_URL("eu.essi_lab.vlab.queue.server", false),
	BP_RUN_QUEQUE_KUBEMQ_CLIENTID("eu.essi_lab.vlab.queue.kubemq.clientid", true),
	BP_RUN_QUEQUE_SERVICE_TYPE("eu.essi_lab.vlab.queue.service.type", false),

	AWS_ES_REGION("eu.essi_lab.vlab.aws.es.region", false),

	AWS_S3_SECRET_KEY("eu.essi_lab.vlab.aws.s3.secretKey", true),
	AWS_S3_ACCESS_KEY("eu.essi_lab.vlab.aws.s3.accessKey", true),
	AWS_BUCKET_REGION("eu.essi_lab.vlab.aws.s3.region", false),
	AWS_S3_SERVICEURL("eu.essi_lab.vlab.aws.s3.url", false),
	AWS_S3_BPRUN_STATUS_BUCKET("eu.essi_lab.vlab.storage.bprun.status.folder", false),
	AWS_S3_OUTPUT_BUCKET_NAME("eu.essi_lab.vlab.storage.output.folder", false),

	AWS_S3_BP_RUN_BUCKET_NAME("eu.essi_lab.vlab.storage.bprun.folder", false),
	AWS_S3_EXECUTABLE_BP_BUCKET("eu.essi_lab.vlab.storage.ebp.folder", false),

	KUBERNETES_PERSISTENT_VOLUME("eu.essi_lab.vlab.kubernetes.pv", false),
	KUBERNETES_PERSISTENT_VOLUME_CLAIM("eu.essi_lab.vlab.kubernetes.pvc", false),
	KUBERNETES_API_SERVER_URL("eu.essi_lab.vlab.kubernetes.serverurl", false),
	KUBERNETES_AUTH_TOKEN("eu.essi_lab.vlab.kubernetes.token", true),
	KUBERNETES_EXECUTOR_SELECTOR("eu.essi_lab.vlab.kubernetes.executor", false),
	KUBERNETES_CONTROLLER_SELECTOR("eu.essi_lab.vlab.kubernetes.controller", false),
	KUBERNETES_EXECUTOR_TOLERATIONS("eu.essi_lab.vlab.kubernetes.executor.tolerations", false),
	KUBERNETES_CONTROLLER_TOLERATIONS("eu.essi_lab.vlab.kubernetes.controller.tolerations", false),

	STORAGE_ESURL("eu.essi_lab.vlab.storage.es.url", false),
	STORAGE_ES_PWD("eu.essi_lab.vlab.storage.es.pwd", true),
	STORAGE_ES_USER("eu.essi_lab.vlab.storage.es.user", true),
	STORAGE_BP_RUN_STORAGE_TYPE("eu.essi_lab.vlab.storage.bprun.type", false),

	DHUS_USER("eu.essi_lab.vlab.scihub.user", true),
	DHUS_PWD("eu.essi_lab.vlab.scihub.pwd", true),



	LOG_BACKEND_TYPE("eu.essi_lab.vlab.storage.log.type", false);

	private final ConfigurationParameter parameter;
	private final boolean secret;

	BPStaticConfigurationParameters(String p, boolean secret) {
		this(p, secret, null);
	}

	BPStaticConfigurationParameters(String p, boolean secret, String defaulValue) {
		this.parameter = new ConfigurationParameter(p);
		this.parameter.setDefaultValue(defaulValue);
		this.secret = secret;
	}

	public ConfigurationParameter getParameter() {
		return parameter;
	}

	public ConfigurationParameter getParameter(boolean protectSecret) {
		if (protectSecret && this.secret)
			return null;

		return parameter;
	}

}
